import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_page_blocks_hero_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_hero_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_hero_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_hero_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_hero_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_hero_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_content_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_content_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_content_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_content_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_content_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_content_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_faq_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_faq_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_faq_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_faq_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_faq_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_faq_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_logos_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_logos_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_logos_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_logos_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_logos_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_logos_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_page_blocks_blog_section_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum_page_blocks_blog_section_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_blog_section_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_blog_section_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_blog_section_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_blog_section_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum__page_v_blocks_blog_section_section_theme" AS ENUM('light', 'dark', 'light-gray', 'dark-gray');
  CREATE TYPE "public"."enum__page_v_blocks_blog_section_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_blog_section_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_blog_section_section_padding_x" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_blog_section_section_padding_y" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_blog_section_section_max_width" AS ENUM('none', 'base', 'small');
  CREATE TYPE "public"."enum_payload_jobs_log_task_slug" AS ENUM('inline', 'schedulePublish');
  CREATE TYPE "public"."enum_payload_jobs_log_state" AS ENUM('failed', 'succeeded');
  CREATE TYPE "public"."enum_payload_jobs_task_slug" AS ENUM('inline', 'schedulePublish');
  CREATE TABLE "payload_jobs_log" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"executed_at" timestamp(3) with time zone NOT NULL,
  	"completed_at" timestamp(3) with time zone NOT NULL,
  	"task_slug" "enum_payload_jobs_log_task_slug" NOT NULL,
  	"task_i_d" varchar NOT NULL,
  	"input" jsonb,
  	"output" jsonb,
  	"state" "enum_payload_jobs_log_state" NOT NULL,
  	"error" jsonb
  );
  
  CREATE TABLE "payload_jobs" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"input" jsonb,
  	"completed_at" timestamp(3) with time zone,
  	"total_tried" numeric DEFAULT 0,
  	"has_error" boolean DEFAULT false,
  	"error" jsonb,
  	"task_slug" "enum_payload_jobs_task_slug",
  	"queue" varchar DEFAULT 'default',
  	"wait_until" timestamp(3) with time zone,
  	"processing" boolean DEFAULT false,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_theme" "enum_page_blocks_hero_section_theme";
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_margin_top" "enum_page_blocks_hero_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_margin_bottom" "enum_page_blocks_hero_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_padding_x" "enum_page_blocks_hero_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_padding_y" "enum_page_blocks_hero_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_max_width" "enum_page_blocks_hero_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_theme" "enum_page_blocks_text_section_section_theme";
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_margin_top" "enum_page_blocks_text_section_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_margin_bottom" "enum_page_blocks_text_section_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_padding_x" "enum_page_blocks_text_section_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_padding_y" "enum_page_blocks_text_section_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_max_width" "enum_page_blocks_text_section_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_theme" "enum_page_blocks_content_section_theme";
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_margin_top" "enum_page_blocks_content_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_margin_bottom" "enum_page_blocks_content_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_padding_x" "enum_page_blocks_content_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_padding_y" "enum_page_blocks_content_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_max_width" "enum_page_blocks_content_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_theme" "enum_page_blocks_faq_section_theme";
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_margin_top" "enum_page_blocks_faq_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_margin_bottom" "enum_page_blocks_faq_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_padding_x" "enum_page_blocks_faq_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_padding_y" "enum_page_blocks_faq_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_max_width" "enum_page_blocks_faq_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_theme" "enum_page_blocks_testimonials_list_section_theme";
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_margin_top" "enum_page_blocks_testimonials_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_margin_bottom" "enum_page_blocks_testimonials_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_padding_x" "enum_page_blocks_testimonials_list_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_padding_y" "enum_page_blocks_testimonials_list_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_max_width" "enum_page_blocks_testimonials_list_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_theme" "enum_page_blocks_cards_grid_section_theme";
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_margin_top" "enum_page_blocks_cards_grid_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_margin_bottom" "enum_page_blocks_cards_grid_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_padding_x" "enum_page_blocks_cards_grid_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_padding_y" "enum_page_blocks_cards_grid_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_max_width" "enum_page_blocks_cards_grid_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_theme" "enum_page_blocks_carousel_section_theme";
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_margin_top" "enum_page_blocks_carousel_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_margin_bottom" "enum_page_blocks_carousel_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_padding_x" "enum_page_blocks_carousel_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_padding_y" "enum_page_blocks_carousel_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_max_width" "enum_page_blocks_carousel_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_theme" "enum_page_blocks_logos_section_theme";
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_margin_top" "enum_page_blocks_logos_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_margin_bottom" "enum_page_blocks_logos_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_padding_x" "enum_page_blocks_logos_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_padding_y" "enum_page_blocks_logos_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_max_width" "enum_page_blocks_logos_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_theme" "enum_page_blocks_links_list_section_theme";
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_margin_top" "enum_page_blocks_links_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_margin_bottom" "enum_page_blocks_links_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_padding_x" "enum_page_blocks_links_list_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_padding_y" "enum_page_blocks_links_list_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_max_width" "enum_page_blocks_links_list_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_blog_section" ADD COLUMN "section_theme" "enum_page_blocks_blog_section_section_theme";
  ALTER TABLE "page_blocks_blog_section" ADD COLUMN "section_margin_top" "enum_page_blocks_blog_section_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_blog_section" ADD COLUMN "section_margin_bottom" "enum_page_blocks_blog_section_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_blog_section" ADD COLUMN "section_padding_x" "enum_page_blocks_blog_section_section_padding_x" DEFAULT 'base';
  ALTER TABLE "page_blocks_blog_section" ADD COLUMN "section_padding_y" "enum_page_blocks_blog_section_section_padding_y" DEFAULT 'base';
  ALTER TABLE "page_blocks_blog_section" ADD COLUMN "section_max_width" "enum_page_blocks_blog_section_section_max_width" DEFAULT 'base';
  ALTER TABLE "page_blocks_blog_section" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_theme" "enum__page_v_blocks_hero_section_theme";
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_margin_top" "enum__page_v_blocks_hero_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_hero_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_padding_x" "enum__page_v_blocks_hero_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_padding_y" "enum__page_v_blocks_hero_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_max_width" "enum__page_v_blocks_hero_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_theme" "enum__page_v_blocks_text_section_section_theme";
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_margin_top" "enum__page_v_blocks_text_section_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_text_section_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_padding_x" "enum__page_v_blocks_text_section_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_padding_y" "enum__page_v_blocks_text_section_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_max_width" "enum__page_v_blocks_text_section_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_theme" "enum__page_v_blocks_content_section_theme";
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_margin_top" "enum__page_v_blocks_content_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_content_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_padding_x" "enum__page_v_blocks_content_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_padding_y" "enum__page_v_blocks_content_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_max_width" "enum__page_v_blocks_content_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_theme" "enum__page_v_blocks_faq_section_theme";
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_margin_top" "enum__page_v_blocks_faq_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_faq_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_padding_x" "enum__page_v_blocks_faq_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_padding_y" "enum__page_v_blocks_faq_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_max_width" "enum__page_v_blocks_faq_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_theme" "enum__page_v_blocks_testimonials_list_section_theme";
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_margin_top" "enum__page_v_blocks_testimonials_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_testimonials_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_padding_x" "enum__page_v_blocks_testimonials_list_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_padding_y" "enum__page_v_blocks_testimonials_list_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_max_width" "enum__page_v_blocks_testimonials_list_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_theme" "enum__page_v_blocks_cards_grid_section_theme";
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_margin_top" "enum__page_v_blocks_cards_grid_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_cards_grid_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_padding_x" "enum__page_v_blocks_cards_grid_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_padding_y" "enum__page_v_blocks_cards_grid_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_max_width" "enum__page_v_blocks_cards_grid_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_theme" "enum__page_v_blocks_carousel_section_theme";
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_margin_top" "enum__page_v_blocks_carousel_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_carousel_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_padding_x" "enum__page_v_blocks_carousel_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_padding_y" "enum__page_v_blocks_carousel_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_max_width" "enum__page_v_blocks_carousel_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_theme" "enum__page_v_blocks_logos_section_theme";
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_margin_top" "enum__page_v_blocks_logos_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_logos_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_padding_x" "enum__page_v_blocks_logos_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_padding_y" "enum__page_v_blocks_logos_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_max_width" "enum__page_v_blocks_logos_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_theme" "enum__page_v_blocks_links_list_section_theme";
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_margin_top" "enum__page_v_blocks_links_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_links_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_padding_x" "enum__page_v_blocks_links_list_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_padding_y" "enum__page_v_blocks_links_list_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_max_width" "enum__page_v_blocks_links_list_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_blog_section" ADD COLUMN "section_theme" "enum__page_v_blocks_blog_section_section_theme";
  ALTER TABLE "_page_v_blocks_blog_section" ADD COLUMN "section_margin_top" "enum__page_v_blocks_blog_section_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_blog_section" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_blog_section_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_blog_section" ADD COLUMN "section_padding_x" "enum__page_v_blocks_blog_section_section_padding_x" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_blog_section" ADD COLUMN "section_padding_y" "enum__page_v_blocks_blog_section_section_padding_y" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_blog_section" ADD COLUMN "section_max_width" "enum__page_v_blocks_blog_section_section_max_width" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_blog_section" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "payload_jobs_log" ADD CONSTRAINT "payload_jobs_log_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."payload_jobs"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_jobs_log_order_idx" ON "payload_jobs_log" USING btree ("_order");
  CREATE INDEX "payload_jobs_log_parent_id_idx" ON "payload_jobs_log" USING btree ("_parent_id");
  CREATE INDEX "payload_jobs_completed_at_idx" ON "payload_jobs" USING btree ("completed_at");
  CREATE INDEX "payload_jobs_total_tried_idx" ON "payload_jobs" USING btree ("total_tried");
  CREATE INDEX "payload_jobs_has_error_idx" ON "payload_jobs" USING btree ("has_error");
  CREATE INDEX "payload_jobs_task_slug_idx" ON "payload_jobs" USING btree ("task_slug");
  CREATE INDEX "payload_jobs_queue_idx" ON "payload_jobs" USING btree ("queue");
  CREATE INDEX "payload_jobs_wait_until_idx" ON "payload_jobs" USING btree ("wait_until");
  CREATE INDEX "payload_jobs_processing_idx" ON "payload_jobs" USING btree ("processing");
  CREATE INDEX "payload_jobs_updated_at_idx" ON "payload_jobs" USING btree ("updated_at");
  CREATE INDEX "payload_jobs_created_at_idx" ON "payload_jobs" USING btree ("created_at");
  ALTER TABLE "page_blocks_hero" ADD CONSTRAINT "page_blocks_hero_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_text_section" ADD CONSTRAINT "page_blocks_text_section_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_content" ADD CONSTRAINT "page_blocks_content_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_faq" ADD CONSTRAINT "page_blocks_faq_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_testimonials_list" ADD CONSTRAINT "page_blocks_testimonials_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_cards_grid" ADD CONSTRAINT "page_blocks_cards_grid_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_carousel" ADD CONSTRAINT "page_blocks_carousel_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_logos" ADD CONSTRAINT "page_blocks_logos_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_links_list" ADD CONSTRAINT "page_blocks_links_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_blog_section" ADD CONSTRAINT "page_blocks_blog_section_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_hero" ADD CONSTRAINT "_page_v_blocks_hero_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_text_section" ADD CONSTRAINT "_page_v_blocks_text_section_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_content" ADD CONSTRAINT "_page_v_blocks_content_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_faq" ADD CONSTRAINT "_page_v_blocks_faq_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD CONSTRAINT "_page_v_blocks_testimonials_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD CONSTRAINT "_page_v_blocks_cards_grid_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_carousel" ADD CONSTRAINT "_page_v_blocks_carousel_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_logos" ADD CONSTRAINT "_page_v_blocks_logos_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_links_list" ADD CONSTRAINT "_page_v_blocks_links_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_blog_section" ADD CONSTRAINT "_page_v_blocks_blog_section_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "page_blocks_hero_section_section_background_image_idx" ON "page_blocks_hero" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_text_section_section_section_background_imag_idx" ON "page_blocks_text_section" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_content_section_section_background_image_idx" ON "page_blocks_content" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_faq_section_section_background_image_idx" ON "page_blocks_faq" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_testimonials_list_section_section_background_idx" ON "page_blocks_testimonials_list" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_cards_grid_section_section_background_image_idx" ON "page_blocks_cards_grid" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_carousel_section_section_background_image_idx" ON "page_blocks_carousel" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_logos_section_section_background_image_idx" ON "page_blocks_logos" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_links_list_section_section_background_image_idx" ON "page_blocks_links_list" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_blog_section_section_section_background_imag_idx" ON "page_blocks_blog_section" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_hero_section_section_background_image_idx" ON "_page_v_blocks_hero" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_text_section_section_section_background_i_idx" ON "_page_v_blocks_text_section" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_content_section_section_background_image_idx" ON "_page_v_blocks_content" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_faq_section_section_background_image_idx" ON "_page_v_blocks_faq" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_testimonials_list_section_section_backgro_idx" ON "_page_v_blocks_testimonials_list" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_cards_grid_section_section_background_ima_idx" ON "_page_v_blocks_cards_grid" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_carousel_section_section_background_image_idx" ON "_page_v_blocks_carousel" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_logos_section_section_background_image_idx" ON "_page_v_blocks_logos" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_links_list_section_section_background_ima_idx" ON "_page_v_blocks_links_list" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_blog_section_section_section_background_i_idx" ON "_page_v_blocks_blog_section" USING btree ("section_background_image_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload_jobs_log" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_jobs" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "payload_jobs_log" CASCADE;
  DROP TABLE "payload_jobs" CASCADE;
  ALTER TABLE "page_blocks_hero" DROP CONSTRAINT "page_blocks_hero_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_text_section" DROP CONSTRAINT "page_blocks_text_section_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_content" DROP CONSTRAINT "page_blocks_content_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_faq" DROP CONSTRAINT "page_blocks_faq_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_testimonials_list" DROP CONSTRAINT "page_blocks_testimonials_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_cards_grid" DROP CONSTRAINT "page_blocks_cards_grid_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_carousel" DROP CONSTRAINT "page_blocks_carousel_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_logos" DROP CONSTRAINT "page_blocks_logos_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_links_list" DROP CONSTRAINT "page_blocks_links_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_blog_section" DROP CONSTRAINT "page_blocks_blog_section_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_hero" DROP CONSTRAINT "_page_v_blocks_hero_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_text_section" DROP CONSTRAINT "_page_v_blocks_text_section_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_content" DROP CONSTRAINT "_page_v_blocks_content_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_faq" DROP CONSTRAINT "_page_v_blocks_faq_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP CONSTRAINT "_page_v_blocks_testimonials_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_cards_grid" DROP CONSTRAINT "_page_v_blocks_cards_grid_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_carousel" DROP CONSTRAINT "_page_v_blocks_carousel_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_logos" DROP CONSTRAINT "_page_v_blocks_logos_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_links_list" DROP CONSTRAINT "_page_v_blocks_links_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_blog_section" DROP CONSTRAINT "_page_v_blocks_blog_section_section_background_image_id_media_id_fk";
  
  DROP INDEX "page_blocks_hero_section_section_background_image_idx";
  DROP INDEX "page_blocks_text_section_section_section_background_imag_idx";
  DROP INDEX "page_blocks_content_section_section_background_image_idx";
  DROP INDEX "page_blocks_faq_section_section_background_image_idx";
  DROP INDEX "page_blocks_testimonials_list_section_section_background_idx";
  DROP INDEX "page_blocks_cards_grid_section_section_background_image_idx";
  DROP INDEX "page_blocks_carousel_section_section_background_image_idx";
  DROP INDEX "page_blocks_logos_section_section_background_image_idx";
  DROP INDEX "page_blocks_links_list_section_section_background_image_idx";
  DROP INDEX "page_blocks_blog_section_section_section_background_imag_idx";
  DROP INDEX "_page_v_blocks_hero_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_text_section_section_section_background_i_idx";
  DROP INDEX "_page_v_blocks_content_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_faq_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_testimonials_list_section_section_backgro_idx";
  DROP INDEX "_page_v_blocks_cards_grid_section_section_background_ima_idx";
  DROP INDEX "_page_v_blocks_carousel_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_logos_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_links_list_section_section_background_ima_idx";
  DROP INDEX "_page_v_blocks_blog_section_section_section_background_i_idx";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_blog_section" DROP COLUMN "section_theme";
  ALTER TABLE "page_blocks_blog_section" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_blog_section" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_blog_section" DROP COLUMN "section_padding_x";
  ALTER TABLE "page_blocks_blog_section" DROP COLUMN "section_padding_y";
  ALTER TABLE "page_blocks_blog_section" DROP COLUMN "section_max_width";
  ALTER TABLE "page_blocks_blog_section" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_blog_section" DROP COLUMN "section_theme";
  ALTER TABLE "_page_v_blocks_blog_section" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_blog_section" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_blog_section" DROP COLUMN "section_padding_x";
  ALTER TABLE "_page_v_blocks_blog_section" DROP COLUMN "section_padding_y";
  ALTER TABLE "_page_v_blocks_blog_section" DROP COLUMN "section_max_width";
  ALTER TABLE "_page_v_blocks_blog_section" DROP COLUMN "section_background_image_id";
  DROP TYPE "public"."enum_page_blocks_hero_section_theme";
  DROP TYPE "public"."enum_page_blocks_hero_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_hero_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_hero_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_hero_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_hero_section_max_width";
  DROP TYPE "public"."enum_page_blocks_text_section_section_theme";
  DROP TYPE "public"."enum_page_blocks_text_section_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_text_section_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_text_section_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_text_section_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_text_section_section_max_width";
  DROP TYPE "public"."enum_page_blocks_content_section_theme";
  DROP TYPE "public"."enum_page_blocks_content_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_content_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_content_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_content_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_content_section_max_width";
  DROP TYPE "public"."enum_page_blocks_faq_section_theme";
  DROP TYPE "public"."enum_page_blocks_faq_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_faq_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_faq_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_faq_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_faq_section_max_width";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_theme";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_max_width";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_theme";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_max_width";
  DROP TYPE "public"."enum_page_blocks_carousel_section_theme";
  DROP TYPE "public"."enum_page_blocks_carousel_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_carousel_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_carousel_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_carousel_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_carousel_section_max_width";
  DROP TYPE "public"."enum_page_blocks_logos_section_theme";
  DROP TYPE "public"."enum_page_blocks_logos_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_logos_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_logos_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_logos_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_logos_section_max_width";
  DROP TYPE "public"."enum_page_blocks_links_list_section_theme";
  DROP TYPE "public"."enum_page_blocks_links_list_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_links_list_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_links_list_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_links_list_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_links_list_section_max_width";
  DROP TYPE "public"."enum_page_blocks_blog_section_section_theme";
  DROP TYPE "public"."enum_page_blocks_blog_section_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_blog_section_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_blog_section_section_padding_x";
  DROP TYPE "public"."enum_page_blocks_blog_section_section_padding_y";
  DROP TYPE "public"."enum_page_blocks_blog_section_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_content_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_content_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_content_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_content_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_content_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_content_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_max_width";
  DROP TYPE "public"."enum__page_v_blocks_blog_section_section_theme";
  DROP TYPE "public"."enum__page_v_blocks_blog_section_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_blog_section_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_blog_section_section_padding_x";
  DROP TYPE "public"."enum__page_v_blocks_blog_section_section_padding_y";
  DROP TYPE "public"."enum__page_v_blocks_blog_section_section_max_width";
  DROP TYPE "public"."enum_payload_jobs_log_task_slug";
  DROP TYPE "public"."enum_payload_jobs_log_state";
  DROP TYPE "public"."enum_payload_jobs_task_slug";`)
}
