/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    page: Page;
    categories: Category;
    authors: Author;
    posts: Post;
    testimonials: Testimonial;
    header: Header;
    footer: Footer;
    redirects: Redirect;
    presets: Preset;
    comments: Comment;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media' | 'page';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    page: PageSelect<false> | PageSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    presets: PresetsSelect<false> | PresetsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'site-settings': SiteSetting;
    _abManifest: _AbManifest;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    _abManifest: _AbManifestSelect<false> | _AbManifestSelect<true>;
  };
  locale: 'en' | 'es';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The name of the user
   */
  name: string;
  /**
   * The role of the user
   */
  role: 'admin' | 'author' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Use this file as default when no image is selected.
   */
  defaultFor?: 'platform_default'[] | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
      | {
          relationTo?: 'page';
          value: number | Page;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('media' | 'page')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page".
 */
export interface Page {
  id: number;
  _abPassPercentage?: number | null;
  /**
   * The title of the page
   */
  title: string;
  /**
   * The header to display on the page
   */
  header?: (number | null) | Header;
  /**
   * The footer to display on the page
   */
  footer?: (number | null) | Footer;
  blocks: (
    | HeroBlock
    | TextSectionBlock
    | ContentBlock
    | FaqBlock
    | TestimonialsListBlock
    | CardsGridBlock
    | CarouselBlock
    | LogosBlock
    | LinksListBlock
    | BlogSectionBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The original page this variant belongs to.
   */
  _abVariantOf?: (number | null) | Page;
  _abVariantPercentages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * The name of the header
   */
  name?: string | null;
  /**
   * The logo to display in the header
   */
  logo: number | Media;
  /**
   * Navigation items in the header (up to 6 items)
   */
  navItems?:
    | {
        /**
         * Link settings
         */
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'page';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Provide a short introduction for the related posts section
   */
  relatedPostsIntro: string;
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  publishedAt?: string | null;
  authors?: (number | Author)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * The name of the author
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The name of the footer
   */
  name: string;
  /**
   * The logo to display in the footer
   */
  logo: number | Media;
  /**
   * Footer navigation links (up to 10 items)
   */
  links?:
    | {
        /**
         * Link settings
         */
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'page';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Footer body text
   */
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Copyright text shown at the bottom
   */
  copywriteText?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  title?: string | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  actions?:
    | {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?:
          | ({
              relationTo: 'page';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        label: string;
        /**
         * Choose how the link should be rendered.
         */
        appearance?: ('default' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  image: {
    image: number | Media;
    aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
  };
  enabled?: boolean | null;
  color?: ('black' | 'white') | null;
  /**
   * Overlay opacity (0-100)
   */
  opacity?: number | null;
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextSectionBlock".
 */
export interface TextSectionBlock {
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  heading?: string | null;
  layout: 'image-text' | 'text-image';
  image: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading: string;
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsListBlock".
 */
export interface TestimonialsListBlock {
  heading?: string | null;
  subheading?: string | null;
  testimonialItems?:
    | {
        testimonial: number | Testimonial;
        id?: string | null;
      }[]
    | null;
  /**
   * The duration of the animation in seconds. Default is 60 seconds.
   */
  duration?: number | null;
  showRating?: boolean | null;
  showAvatar?: boolean | null;
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  company?: string | null;
  position?: string | null;
  avatar?: (number | null) | Media;
  content: string;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsGridBlock".
 */
export interface CardsGridBlock {
  columns?: number | null;
  items: {
    title: string;
    description?: string | null;
    image?: {
      image?: (number | null) | Media;
      aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
    };
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label?: string | null;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'outline') | null;
    };
    alignVariant?: ('left' | 'center' | 'right') | null;
    rounded?: ('none' | 'large') | null;
    backgroundColor?: ('none' | 'light' | 'dark' | 'light-gray' | 'dark-gray' | 'gradient-2') | null;
    id?: string | null;
  }[];
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  effect?: ('slide' | 'fade' | 'cube' | 'flip' | 'coverflow' | 'cards') | null;
  slides: {
    image: {
      image: number | Media;
      aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
    };
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  alignVariant?: ('left' | 'center' | 'right') | null;
  items: {
    image: {
      image: number | Media;
      aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
    };
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
    };
    id?: string | null;
  }[];
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksListBlock".
 */
export interface LinksListBlock {
  alignVariant?: ('left' | 'center' | 'right') | null;
  links: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'outline') | null;
    };
    id?: string | null;
  }[];
  section?: {
    theme?: ('light' | 'dark' | 'light-gray' | 'dark-gray') | null;
    marginTop?: ('none' | 'base' | 'large') | null;
    marginBottom?: ('none' | 'base' | 'large') | null;
    paddingX?: ('none' | 'base' | 'large') | null;
    paddingY?: ('none' | 'base' | 'large') | null;
    maxWidth?: ('none' | 'base' | 'small') | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'linksList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogSectionBlock".
 */
export interface BlogSectionBlock {
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  style?: ('three-column' | 'three-column-with-images' | 'three-column-with-background-images') | null;
  /**
   * Aspect ratio applied to all post images in this section
   */
  aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
  postsLimit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Latin letters, numbers, / - _ . ~ only. No spaces. Stored as lowercase with leading slash.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'page';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  /**
   * Choose the redirect type. 307 - temporary, 308 - permanent.
   */
  type: '307' | '308';
  /**
   * Whether the redirect is active.
   */
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * One preset = one type. After choosing type, fill the matching section below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presets".
 */
export interface Preset {
  id: number;
  name: string;
  /**
   * The preview image for the preset
   */
  preview?: (number | null) | Media;
  /**
   * Choose type — only the matching section below will be shown.
   */
  type: 'hero' | 'testimonialsList';
  hero?: {
    title?: string | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    actions?:
      | {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'page';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          id?: string | null;
        }[]
      | null;
    image: {
      image: number | Media;
      aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
    };
    enabled?: boolean | null;
    color?: ('black' | 'white') | null;
    /**
     * Overlay opacity (0-100)
     */
    opacity?: number | null;
  };
  testimonialsList?: {
    heading?: string | null;
    subheading?: string | null;
    testimonialItems?:
      | {
          testimonial: number | Testimonial;
          id?: string | null;
        }[]
      | null;
    /**
     * The duration of the animation in seconds. Default is 60 seconds.
     */
    duration?: number | null;
    showRating?: boolean | null;
    showAvatar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  documentId?: number | null;
  collectionSlug?: string | null;
  /**
   * Slug of the Payload global being commented on. Null = collection document comment.
   */
  globalSlug?: string | null;
  /**
   * Dot-notation path of the field being commented on. Null = document-level.
   */
  fieldPath?: string | null;
  /**
   * Locale for field-level comments. Null = document-level (shown in all locales).
   */
  locale?: string | null;
  text: string;
  mentions?:
    | {
        user: number | User;
        id?: string | null;
      }[]
    | null;
  author: number | User;
  isResolved?: boolean | null;
  resolvedBy?: (number | null) | User;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'page';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'header';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'presets';
        value: number | Preset;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  defaultFor?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_select".
 */
export interface PageSelect<T extends boolean = true> {
  _abPassPercentage?: T;
  title?: T;
  header?: T;
  footer?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        textSection?: T | TextSectionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        testimonialsList?: T | TestimonialsListBlockSelect<T>;
        cardsGrid?: T | CardsGridBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        logos?: T | LogosBlockSelect<T>;
        linksList?: T | LinksListBlockSelect<T>;
        blogSection?: T | BlogSectionBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  _abVariantOf?: T;
  _abVariantPercentages?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  richText?: T;
  actions?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        id?: T;
      };
  image?:
    | T
    | {
        image?: T;
        aspectRatio?: T;
      };
  enabled?: T;
  color?: T;
  opacity?: T;
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextSectionBlock_select".
 */
export interface TextSectionBlockSelect<T extends boolean = true> {
  text?: T;
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  heading?: T;
  layout?: T;
  image?: T;
  content?: T;
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsListBlock_select".
 */
export interface TestimonialsListBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  testimonialItems?:
    | T
    | {
        testimonial?: T;
        id?: T;
      };
  duration?: T;
  showRating?: T;
  showAvatar?: T;
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsGridBlock_select".
 */
export interface CardsGridBlockSelect<T extends boolean = true> {
  columns?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        image?:
          | T
          | {
              image?: T;
              aspectRatio?: T;
            };
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        alignVariant?: T;
        rounded?: T;
        backgroundColor?: T;
        id?: T;
      };
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  text?: T;
  effect?: T;
  slides?:
    | T
    | {
        image?:
          | T
          | {
              image?: T;
              aspectRatio?: T;
            };
        text?: T;
        id?: T;
      };
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock_select".
 */
export interface LogosBlockSelect<T extends boolean = true> {
  alignVariant?: T;
  items?:
    | T
    | {
        image?:
          | T
          | {
              image?: T;
              aspectRatio?: T;
            };
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksListBlock_select".
 */
export interface LinksListBlockSelect<T extends boolean = true> {
  alignVariant?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  section?:
    | T
    | {
        theme?: T;
        marginTop?: T;
        marginBottom?: T;
        paddingX?: T;
        paddingY?: T;
        maxWidth?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogSectionBlock_select".
 */
export interface BlogSectionBlockSelect<T extends boolean = true> {
  text?: T;
  style?: T;
  aspectRatio?: T;
  postsLimit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPostsIntro?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  publishedAt?: T;
  authors?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  company?: T;
  position?: T;
  avatar?: T;
  content?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  text?: T;
  copywriteText?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presets_select".
 */
export interface PresetsSelect<T extends boolean = true> {
  name?: T;
  preview?: T;
  type?: T;
  hero?:
    | T
    | {
        title?: T;
        richText?: T;
        actions?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              id?: T;
            };
        image?:
          | T
          | {
              image?: T;
              aspectRatio?: T;
            };
        enabled?: T;
        color?: T;
        opacity?: T;
      };
  testimonialsList?:
    | T
    | {
        heading?: T;
        subheading?: T;
        testimonialItems?:
          | T
          | {
              testimonial?: T;
              id?: T;
            };
        duration?: T;
        showRating?: T;
        showAvatar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  documentId?: T;
  collectionSlug?: T;
  globalSlug?: T;
  fieldPath?: T;
  locale?: T;
  text?: T;
  mentions?:
    | T
    | {
        user?: T;
        id?: T;
      };
  author?: T;
  isResolved?: T;
  resolvedBy?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The name of your website
   */
  siteName?: string | null;
  /**
   * The header to display on the blog page
   */
  header?: (number | null) | Header;
  /**
   * The footer to display on the blog page
   */
  footer?: (number | null) | Footer;
  /**
   * Logo displayed in the admin panel sidebar (recommended: SVG or PNG, ~150x40px)
   */
  adminLogo?: (number | null) | Media;
  /**
   * Icon displayed when sidebar is collapsed (recommended: SVG or PNG, 32x32px)
   */
  adminIcon?: (number | null) | Media;
  /**
   * Character used to separate page title from site name
   */
  seoTitleSeparator?: ('|' | '-' | '•') | null;
  /**
   * Text added after separator (defaults to Site Name if empty)
   */
  seoTitleSuffix?: string | null;
  /**
   * Fallback title for Open Graph when page has no title
   */
  defaultOgTitle?: string | null;
  /**
   * Fallback description when page has no description
   */
  defaultDescription?: string | null;
  /**
   * Fallback description for Open Graph (uses Meta Description if empty)
   */
  defaultOgDescription?: string | null;
  /**
   * Fallback image for social media sharing
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Site name for Open Graph. Defaults to Site Name if empty
   */
  ogSiteName?: string | null;
  /**
   * Twitter/X username for the website (e.g., @yoursite)
   */
  twitterSite?: string | null;
  /**
   * Default Twitter/X username for content creator (e.g., @author)
   */
  twitterCreator?: string | null;
  /**
   * Type of Twitter Card to display
   */
  defaultTwitterCard?: ('summary_large_image' | 'summary') | null;
  /**
   * Heading displayed on 404 page
   */
  notFoundTitle?: string | null;
  /**
   * Text displayed on 404 page
   */
  notFoundDescription?: string | null;
  blog?: {
    /**
     * The main title for the blog page
     */
    blogTitle?: string | null;
    /**
     * Used for meta description if not overridden
     */
    blogDescription?: string | null;
    blogMeta?: {
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (number | null) | Media;
      description?: string | null;
      /**
       * Allow search engines to index this page
       */
      robots?: ('index' | 'noindex') | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "_abManifest".
 */
export interface _AbManifest {
  id: number;
  /**
   * A/B testing manifest. Managed automatically — do not edit manually.
   */
  manifest?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  header?: T;
  footer?: T;
  adminLogo?: T;
  adminIcon?: T;
  seoTitleSeparator?: T;
  seoTitleSuffix?: T;
  defaultOgTitle?: T;
  defaultDescription?: T;
  defaultOgDescription?: T;
  defaultOgImage?: T;
  ogSiteName?: T;
  twitterSite?: T;
  twitterCreator?: T;
  defaultTwitterCard?: T;
  notFoundTitle?: T;
  notFoundDescription?: T;
  blog?:
    | T
    | {
        blogTitle?: T;
        blogDescription?: T;
        blogMeta?:
          | T
          | {
              title?: T;
              image?: T;
              description?: T;
              robots?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "_abManifest_select".
 */
export interface _AbManifestSelect<T extends boolean = true> {
  manifest?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'page';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: 'site-settings' | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsGridInlineBlock".
 */
export interface CardsGridInlineBlock {
  columns?: number | null;
  items: {
    title: string;
    description?: string | null;
    image?: {
      image?: (number | null) | Media;
      aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
    };
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label?: string | null;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'outline') | null;
    };
    alignVariant?: ('left' | 'center' | 'right') | null;
    rounded?: ('none' | 'large') | null;
    backgroundColor?: ('none' | 'light' | 'dark' | 'light-gray' | 'dark-gray' | 'gradient-2') | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardsGridInline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosInlineBlock".
 */
export interface LogosInlineBlock {
  alignVariant?: ('left' | 'center' | 'right') | null;
  items: {
    image: {
      image: number | Media;
      aspectRatio?: ('16/9' | '3/2' | '4/3' | '1/1' | '9/16' | '1/2' | '4/1' | '3/1' | 'auto') | null;
    };
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logosInline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksListInlineBlock".
 */
export interface LinksListInlineBlock {
  alignVariant?: ('left' | 'center' | 'right') | null;
  links: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'outline') | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'linksListInline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}